### ISSUE TITLE
CSS syntax highlighting issues

### ISSUE THREAD

**Issue by kirbyfan64** [nilnor/howl#46]
This is highlighted correctly:

```css
a:visited { color: blue }
```

but this strips the color from `a`, `visited`, and `color`:

```css
a:visited { color: blue; }
```
